apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
    app.kubernetes.io/name: grafana
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
