apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-server
  labels:
    app: scdf-server
spec:
  selector:
    matchLabels:
      app: scdf-server
      app.kubernetes.io/name: scdf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scdf-server
        app.kubernetes.io/name: scdf-server
    spec:
      containers:
      - name: scdf-server
        image: springcloud/spring-cloud-dataflow-server:2.8.1
        imagePullPolicy: Always
        volumeMounts:
          - name: config
            mountPath: /workspace/config
            readOnly: true
          - name: database
            mountPath: /etc/secrets/database
            readOnly: true
          #- name: test2
          #  mountPath: /tmp/test2
          #  readOnly: false
        ports:
        - containerPort: 8441
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8441
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: /management/info
            port: 8441
          initialDelaySeconds: 90
        resources:
          limits:
            cpu: 4.0
            memory: 8192Mi
          requests:
            cpu: 0.5
            memory: 1024Mi
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: SERVER_PORT
          value: '8441'
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: 'false'
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_DATAFLOW_TASK_COMPOSEDTASKRUNNER_URI
          value: 'docker://springcloud/spring-cloud-dataflow-composed-task-runner:2.8.1'
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLE_API
          value: 'false'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: 'false'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
          value: /etc/secrets
        - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
          value: 'http://${SCDF_SERVER_SERVICE_HOST}:${SCDF_SERVER_SERVICE_PORT}'
          # Provide the Skipper service location
        - name: SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI
          value: 'http://${SKIPPER_SERVICE_HOST}:${SKIPPER_SERVICE_PORT}/api'
          # Add Maven repo for metadata artifact resolution for all stream apps
        - name: SPRING_APPLICATION_JSON
          value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } } }"
      #initContainers:
      #- name: initpv
      #  image: springcloud/spring-cloud-dataflow-server:2.8.1
      #  command: ['sh', '-c', 'mkdir /tmp/data; chmod 777 -R /tmp/data/']
      serviceAccountName: scdf-sa
      volumes:
        - name: config
          configMap:
            name: scdf-server
            items:
            - key: application.yaml
              path: application.yaml
        - name: database
          secret:
            secretName: mysql
        #- name: test2
        #  persistentVolumeClaim:
        #    claimName: task-pv-claimr
