kind: Service
apiVersion: v1
metadata:
  name: scdf-service
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  # If you are running k8s on a local dev box or using minikube, you can use type NodePort instead
  #type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8441
      protocol: TCP
      #name: scdf-server
  type: NodePort
  selector:
    app: scdf-server
    app.kubernetes.io/name: scdf-server
