apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    #server:
    #  port: 8443
    #  ssl:
    #    enabled: true
    #    key-alias: dataflow
    #    key-store: /tmp/test2/dataflow.keystore
    #    key-store-type: jks
    #    key-store-password: dataflow
    #    key-password: dataflow
    management:
      metrics:
        export:
          prometheus:
            enabled: true
            rsocket:
              enabled: true
              host: prometheus-proxy
              port: 7001
    spring:
      cloud:
        dataflow:
          metrics.dashboard:
            url: 'http://$grafana'
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        url: jdbc:postgresql://$rds/scdfpersistentdb
        username: adminscdf
        password: ${mysql-root-password}
        driverClassName: org.postgresql.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"

